Safe initial config

diff --git a/snap/hooks/configure b/snap/hooks/configure
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -2,12 +2,14 @@
 
 # Detect failure mode with early core18
 if ! which snapctl > /dev/null; then
-    echo "WARNING: 'snapctl' is missing, configuration will fail."
-    echo "    This should be fixed (in core18) soon."
-    echo "    Workaround: set app to one of:"
-    ls -1 $SNAP/apps/ | sed "s/^/        /"
-    echo "    by editing /var/snap/mir-kiosk-apps/current/config_options"
-    exit 1
+    if [ -e "$SNAP_DATA/config_options" ]; then
+        echo "ERROR: 'snapctl' is missing, configuration will fail."
+        echo "    This should be fixed (in core18) soon."
+        echo "    Workaround: set app to one of:"
+        ls -1 $SNAP/apps/ | sed "s/^/        /"
+        echo "    by editing /var/snap/mir-kiosk-apps/current/config_options"
+        exit 1
+    fi
 fi
 
 app=$(snapctl get app)
